Vagrant.configure("2") do |config|

  config.vm.box = "tdorosz/base-box-ubuntu"
  config.vm.box_version = "{{box_version}}"
  config.vm.hostname = "{{hostname}}"

  config.vm.network :private_network, ip: "{{ip_address}}"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = '{{hostname}}'

    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", path: "provision/init.sh"

end
